import type { Metadata } from "next";
import { museoSans } from "./fonts";

export const metadata: Metadata = {
  title: "Elo7",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={museoSans.className}>{children}</body>
    </html>
  );
}
